# Generated by Django 5.2 on 2025-05-31 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_region_shippingregion_name'),
        ('users', '0002_alter_userprofile_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='orders.shippingregion'),
        ),
    ]
