# Generated by Django 5.2 on 2025-05-10 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usergroup_userprofile_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.usergroup'),
        ),
    ]

