# Generated by Django 5.2 on 2025-05-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='group_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]

