# Generated by Django 5.2 on 2025-05-18 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usergroup_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='group_id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usergroup'),
        ),
    ]

