# Generated by Django 5.2 on 2025-05-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_usergroup_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comopany_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
