# Generated by Django 5.2 on 2025-05-25 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_comopany_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='comopany_name',
            new_name='company_name',
        ),
    ]
