# Generated by Django 5.2 on 2025-05-27 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_shippingregion_shippingfeerule_region'),
        ('users', '0008_rename_comopany_name_userprofile_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='orders.shippingregion'),
        ),
    ]

