services:
  - type: web
    name: order-app
    runtime: python

    startCommand: gunicorn config.wsgi:application
    envVars:
    - key: DJANGO_SETTINGS_MODULE
      value: config.settings
    - key: PYTHON_VERSION
      value: 3.11