services:
  - type: web
    name: order-app
    runtime: python
    buildCommand:  |
      pip install -r requirements.txt
      npm install --prefix theme
      python manage.py tailwind build
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
    - key: DJANGO_SETTINGS_MODULE
      value: config.settings
    - key: PYTHON_VERSION
      value: 3.11