# Generated by Django 5.2 on 2025-05-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistoryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
