# Generated by Django 5.2 on 2025-06-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0002_errmsg_errlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(help_text='メール冒頭や署名など')),
            ],
        ),
    ]
