# Generated by Django 5.2 on 2025-04-28 23:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.PositiveIntegerField()),
                ('max_qty', models.PositiveIntegerField()),
                ('fee', models.PositiveIntegerField()),
                ('tax', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(max_length=10)),
                ('invoice_id', models.CharField(max_length=20, unique=True)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_extax', models.DecimalField(decimal_places=0, max_digits=10)),
                ('tax8', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('shipping_extax', models.DecimalField(decimal_places=0, max_digits=10)),
                ('tax10', models.DecimalField(decimal_places=0, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=0, max_digits=10)),
                ('final_extax', models.DecimalField(decimal_places=0, max_digits=10)),
                ('final_tax', models.DecimalField(decimal_places=0, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='未処理', max_length=50)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('final_total', models.PositiveIntegerField(default=0)),
                ('total_tax', models.PositiveIntegerField(default=0)),
                ('total_shipping_fee', models.PositiveIntegerField(default=0)),
                ('shipping_tax', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('tax', models.PositiveIntegerField(default=0)),
                ('shipping_fee', models.PositiveIntegerField(default=0)),
                ('shipping_tax', models.PositiveIntegerField(default=0)),
                ('delivery_date', models.DateField(default=datetime.date(2025, 4, 28))),
                ('delivery_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('tracking_id', models.CharField(max_length=20, null=True)),
                ('invoice_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='orders.invoice')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productname')),
            ],
        ),
    ]
