# Generated by Django 5.2 on 2025-04-29 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='amount',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='grade',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2025, 4, 29)),
        ),
    ]
