# Generated by Django 5.2 on 2025-05-31 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingregion',
            old_name='region',
            new_name='name',
        ),
    ]
