# Generated by Django 5.2 on 2025-05-27 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_shippingfeerule_shipping_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='shippingfeerule',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_fee_rules', to='orders.shippingregion'),
        ),
    ]

