# Generated by Django 5.2 on 2025-06-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('tentative', '仮注文'), ('received', '確認済み'), ('preparing', '準備中'), ('shipped', '発送済'), ('canceled', 'キャンセル済')], default='tentative', max_length=50),
        ),
    ]
