# Generated by Django 5.2 on 2025-04-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_shippingfeerule_order_total_order_total_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
