# Generated by Django 5.2 on 2025-04-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_final_total_order_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tax',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
