# Generated by Django 5.2 on 2025-06-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_flg',
            field=models.BooleanField(default=False),
        ),
    ]
