# Generated by Django 5.2 on 2025-05-07 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_unit_alter_orderitem_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.date(2025, 5, 7)),
        ),
    ]
