# Generated by Django 5.2 on 2025-04-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_tax',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_tax',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shippingfeerule',
            name='tax',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
