# Generated by Django 5.2 on 2025-06-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_pickup_flg'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_deli_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
