# Generated by Django 5.2 on 2025-04-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_final_tax_order_shipping_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shipping_fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
