# Generated by Django 5.2 on 2025-04-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_shipping_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_fee',
            new_name='total_shipping_fee',
        ),
    ]
