# Generated by Django 5.2 on 2025-04-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_shipping_fee_order_total_shipping_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='final_tax',
            new_name='total_tax',
        ),
    ]
