# Generated by Django 5.2 on 2025-04-13 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_final_tax_order_total_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.date(2025, 4, 13)),
        ),
    ]
