# Generated by Django 5.2 on 2025-04-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_delivery_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipping_tax',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
