# Generated by Django 5.2 on 2025-04-14 13:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_total_order_total_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2025, 4, 14)),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(max_length=10)),
                ('invoice_id', models.CharField(max_length=20, unique=True)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_extax', models.DecimalField(decimal_places=0, max_digits=10)),
                ('tax8', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('shipping_extax', models.DecimalField(decimal_places=0, max_digits=10)),
                ('tax10', models.DecimalField(decimal_places=0, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=0, max_digits=10)),
                ('final_extax', models.DecimalField(decimal_places=0, max_digits=10)),
                ('final_tax', models.DecimalField(decimal_places=0, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='invoice_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='orders.invoice'),
        ),
    ]
