# Generated by Django 5.2 on 2025-04-18 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderitem_delivery_id_alter_orderitem_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2025, 4, 18)),
        ),
    ]
