# Generated by Django 5.2 on 2025-04-19 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orderitem_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='traking_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2025, 4, 19)),
        ),
    ]
