# Generated by Django 5.2 on 2025-04-20 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderitem_traking_id_alter_orderitem_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2025, 4, 20)),
        ),
    ]
