# Generated by Django 5.2 on 2025-04-20 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_orderitem_delivery_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='traking_id',
            new_name='tracking_id',
        ),
    ]
