# Generated by Django 5.2 on 2025-04-21 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_rename_traking_id_orderitem_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2025, 4, 21)),
        ),
    ]
