# Generated by Django 5.2 on 2025-05-31 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('available', '受付中'), ('closed', '準備中')], default='available', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('unit', models.CharField(default='4.3kg/箱', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.PositiveIntegerField()),
                ('tax10_flg', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', '受付中'), ('closed', '準備中')], default='closed', max_length=50)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.fruitkind')),
                ('user_group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.usergroup')),
            ],
        ),
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('season', models.CharField(max_length=50)),
                ('sort_no', models.PositiveIntegerField()),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.fruitkind')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDeliveryDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_dates', to='products.productname')),
            ],
        ),
    ]
