# Generated by Django 5.2 on 2025-05-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productname',
            name='status',
            field=models.CharField(choices=[('available', '在庫あり'), ('preorder', '予約受付中'), ('closed', 'シーズン終了')], default='available', max_length=20),
        ),
    ]

