# Generated by Django 5.2 on 2025-05-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetable',
            name='status',
            field=models.CharField(choices=[('available', '受付中'), ('closed', '準備中')], default='closed', max_length=50),
        ),
    ]
