# Generated by Django 5.2 on 2025-05-10 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productname_status'),
        ('users', '0003_usergroup_userprofile_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetable',
            name='user_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.usergroup'),
        ),
    ]
