# Generated by Django 5.2 on 2025-05-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productname_status_fruitkind_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruitkind',
            name='status',
        ),
        migrations.AddField(
            model_name='productname',
            name='status',
            field=models.CharField(choices=[('available', '受付中'), ('closed', '準備中')], default='available', max_length=50),
        ),
    ]
