# Generated by Django 5.2 on 2025-05-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_pricetable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetable',
            name='tax10_flg',
            field=models.BooleanField(default=False),
        ),
    ]
