# Generated by Django 5.2 on 2025-04-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
