# Generated by Django 5.2 on 2025-04-11 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tax',
        ),
    ]
