# Generated by Django 5.2 on 2025-05-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_pricetable_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productname',
            name='status',
            field=models.CharField(choices=[('available', '受付中'), ('closed', '準備中')], default='available', max_length=20),
        ),
    ]
