# Generated by Django 5.2 on 2025-04-13 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDeliveryDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_dates', to='products.product')),
            ],
        ),
    ]
