# Generated by Django 5.2 on 2025-05-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productname_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricetable',
            name='amount',
        ),
        migrations.AddField(
            model_name='pricetable',
            name='status',
            field=models.CharField(choices=[('available', '受付中'), ('closed', '準備中')], default='available', max_length=50),
        ),
        migrations.AddField(
            model_name='pricetable',
            name='tax10_flg',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricetable',
            name='weight',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='unit',
            field=models.CharField(default='4.3kg/箱', max_length=20),
        ),
        migrations.AlterField(
            model_name='productname',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productname',
            name='status',
            field=models.CharField(choices=[('available', '受付中'), ('closed', '準備中')], default='available', max_length=50),
        ),
    ]
