# Generated by Django 5.2 on 2025-05-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_pricetable_amount_pricetable_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetable',
            name='deli_unit',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
