# Generated by Django 5.2 on 2025-05-24 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_pricetable_deli_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricetable',
            name='deli_unit',
        ),
    ]

