# Generated by Django 5.2 on 2025-05-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_pricetable_deli_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetable',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
