# Generated by Django 5.2 on 2025-05-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_pricetable_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='productname',
            name='season',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productname',
            name='sort_no',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
